server:
  port: 8888
spring:
  profiles.active: native
  application.name: config-service
  cloud:
    config:
      server:
        native:
          searchLocations: ${CONFIG_LOC:/Users/nik/dev/repo/cloud-play-00/config-service/config}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}